parameters:
#    code_lovers_doctrine_encrypt.example.class: CodeLovers\DoctrineEncryptBundle\Example

services:
#    code_lovers_doctrine_encrypt.example:
#        class: %code_lovers_doctrine_encrypt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
